{{ config(materialized='view') }}

SELECT
    customer_id,
    gender,
    senior_citizen,
    partner,
    dependents,
    tenure_months,
    phone_service,
    multiple_lines,
    internet_service,
    online_security,
    online_backup,
    device_protection,
    tech_support,
    streaming_tv,
    streaming_movies,
    contract,
    paperless_billing,
    payment_method,
    monthly_charges,
    total_charges,
    churn_label,
    churn_value,
    churn_score,
    cltv,
    churn_reason,
    city,
    state,
    country,
    latitude,
    longitude
FROM {{ source('telecom', 'telecom_churn') }}